file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/cppCheck/build)

# ==== START: Configure ====
set(CPPCHECK_CFG_XML_VERSION "1.0")
set(CPPCHECK_CFG_ENCODING "UTF-8")
set(CPPCHECK_CFG_ROOT_DIR "${CMAKE_SOURCE_DIR}")
set(CPPCHECK_CFG_BUILD_DIR "${CMAKE_BINARY_DIR}/cppCheck/build")
set(CPPCHECK_CFG_PLATFORM "unix64")
set(CPPCHECK_CFG_ANALYZE_ALL_VS_CONFIGS "false")
set(CPPCHECK_CFG_CHECK_HEADERS "true")
set(CPPCHECK_CFG_CHECK_UNUSED_TEMPLATES "true")
set(CPPCHECK_CFG_INLINE_SUPPRESSION "true")
set(CPPCHECK_CFG_MAX_CTU_DEPTH "2")
set(CPPCHECK_CFG_MAX_TEMPLATE_RECURSION "100")
set(CPPCHECK_CFG_PROJECT_NAME "${PROJECT_NAME}")
set(CPPCHECK_CFG_CHECK_LEVEL "NORMAL")


set(
    CPPCHECK_CFG_SUPPRESSIONS
    "missingIncludeSystem"
)

# ==== END: Configure ====

set(CPPCHECK_REPORTS_DIR "${CMAKE_BINARY_DIR}/cppCheck/reports")
set(CPPCHECK_REPORTS_XML "${CPP_CHECK_REPORTS_DIR}/report.xml")

set(FILE_CPPCHECK_SOURCES "${CMAKE_BINARY_DIR}/cppCheck/configs/sources_for_cppCheck.txt")
set(FILE_CPPCHECK_INCLUDES "${CMAKE_BINARY_DIR}/cppCheck/configs/includes_for_cppCheck.txt")
set(FILE_CPPCHECK_EXCLUDES "${CMAKE_BINARY_DIR}/cppCheck/configs/excludes_for_cppCheck.txt")
set(FILE_CPPCHECK_SUPPRESS "${CMAKE_BINARY_DIR}/cppCheck/configs/suppress_for_cppCheck.txt")
set(FILE_CPPCHECK_CONFIGS "${CMAKE_BINARY_DIR}/cppCheck/configs/configs_for_cppCheck.txt")

file(WRITE ${FILE_CPPCHECK_SOURCES} "")
file(WRITE ${FILE_CPPCHECK_INCLUDES} "")
file(WRITE ${FILE_CPPCHECK_EXCLUDES} "")
file(WRITE ${FILE_CPPCHECK_SUPPRESS} "")
file(WRITE ${FILE_CPPCHECK_CONFIGS} "")

# ==== START: update configuration text file ====
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_XML_VERSION ${CPPCHECK_CFG_XML_VERSION}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_ENCODING ${CPPCHECK_CFG_ENCODING}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_ROOT_DIR ${CPPCHECK_CFG_ROOT_DIR}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_BUILD_DIR ${CPPCHECK_CFG_BUILD_DIR}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_PLATFORM ${CPPCHECK_CFG_PLATFORM}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_ANALYZE_ALL_VS_CONFIGS ${CPPCHECK_CFG_ANALYZE_ALL_VS_CONFIGS}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_CHECK_HEADERS ${CPPCHECK_CFG_CHECK_HEADERS}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_CHECK_UNUSED_TEMPLATES ${CPPCHECK_CFG_CHECK_UNUSED_TEMPLATES}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_INLINE_SUPPRESSION ${CPPCHECK_CFG_INLINE_SUPPRESSION}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_MAX_CTU_DEPTH ${CPPCHECK_CFG_MAX_CTU_DEPTH}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_MAX_TEMPLATE_RECURSION ${CPPCHECK_CFG_MAX_TEMPLATE_RECURSION}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_PROJECT_NAME ${CPPCHECK_CFG_PROJECT_NAME}\n")
file(APPEND ${FILE_CPPCHECK_CONFIGS} "CPPCHECK_CFG_CHECK_LEVEL ${CPPCHECK_CFG_CHECK_LEVEL}\n")
# ==== END: update configuration text file ====

file(APPEND ${FILE_CPPCHECK_SUPPRESS} "${CPPCHECK_CFG_SUPPRESSIONS}\n")

# Copy bash script to build directory
file(COPY "${REPO_LOC_OTHER_SCRIPTS}/run_cppcheck.sh"
    DESTINATION "${CMAKE_BINARY_DIR}/cppCheck/"
)